### ISSUE TITLE
Is there any way somehow to embed the device library in the host and load from within?

### ISSUE THREAD

**Issue by quickwritereader** [SX-Aurora/veda#17]
Is there any way somehow to embed the device library in the host and load from within?
thanks

**Comment by mergian** [comment]
You mean something like ```cuModuleLoadData(CUmodule*, const void*)```?


No and it is not planned at the moment because libdl does not support to load shared objects directly from memory. It would require to add this functionality to VEOS first.


BUT you can implement that on your own if you like.

1st you need to get your device library into the host code. Easiest way I know of is to use ```ld -r -m elf_x86_64 -b binary your_lib.so --oformat elf64-x86-64 -o your_lib_as_object.o``` and then link the ```your_lib_as_object.o``` to your application/library.

This creates some external symbols (check the object file with ```nm your_lib_as_object.o``` to get the correct names):

```cpp
extern char _binary_your_lib_start[];
extern char _binary_your_lib_end[];
```

**Important**: you can't access them directly, they are no real pointers. Instead their address needs to be reinterpreted as pointer. ```(char*)&_binary_your_lib_start```. More details: https://stackoverflow.com/questions/4158900/embedding-resources-in-executable-using-gcc

2nd you write the contents from that at runtime to a temporary file.

3rd use that file with ```vedaModuleLoad(...)```.

So roughly like this:
```cpp
auto start = (char*)&_binary_your_lib_start;
auto end = (char*)&_binary_your_lib_end;
std::ofstream file("tmplib.so", std::ios::binary);
file.write(start, end-start);
file.close();

VEDAmodule mod;
vedaModuleLoad(&mod, "tmplib.so");
std::remove("tmplib.so");
```

As said, libdl can't load libraries from memory so there is no way around the temporary file.

**Comment by quickwritereader** [comment]
@mergian thanks.
